### ISSUE TITLE
Chinese garbled on Windows platform

### ISSUE THREAD

**Issue by LzIManD** [ShyykoSerhiy/gfm-plugin#102]
code
 ```
#0x05 特别地
```
preview
![preview](http://7xlc1d.com1.z0.glb.clouddn.com/github20160121173124.png)

And, this problem isn't  appeared on Linux platform.

**Comment by ShyykoSerhiy** [comment]
@LzIManD , thanks for submitting this issue. 
Can you please provide more info:
* What operating system you are running?
* Which of JetBrains products you are using: WebStorm, Intellij Idea, PHPStorm, etc.(and versions)?

**Comment by LzIManD** [comment]
OS : Microsoft Windows [version 10.0.10586]
Product: Intellij Idea 15.0.3

**Comment by ShyykoSerhiy** [comment]
Should be fixed in v0.1.9

**Comment by LzIManD** [comment]
Thanks.

2016-02-02 5:46 GMT+08:00 shyyko.serhiy <notifications@github.com>:
