### ISSUE TITLE
Update width of preview to match updated GitHub CSS

### ISSUE THREAD

**Issue by mindplay-dk** [ShyykoSerhiy/gfm-plugin#105]
Since the recent design update on github.com, the inner width of the Markdown content area on the site is now 888px.

They may have made other updates to the CSS affecting Markdown rendered content with this recent update, I'm not sure - but it might be a good idea to do a full update of whatever CSS files were originally copied from github.com to the plugin?

**Comment by ShyykoSerhiy** [comment]
Thx for the tip. Will update css files.

**Comment by mindplay-dk** [comment]
Is there an update coming?

The CSS preview isn't very helpful with the wrong CSS.

I recently used [this script](https://github.com/sindresorhus/generate-github-markdown-css) to download and extract the required CSS - it worked and was no effort at all :-)

**Comment by ShyykoSerhiy** [comment]
Resolved in 0.1.10
