### ISSUE TITLE
Local images are not loaded properly.

### ISSUE THREAD

**Issue by yadavvi91** [ShyykoSerhiy/gfm-plugin#106]
When using an internal image like so ![part11](https://cloud.githubusercontent.com/assets/8291759/12960669/7d8fd0a8-d062-11e5-88fa-f3f4a60f7452.png)

the gfm previewer does not show the image in the intellij plugin 
![part22](https://cloud.githubusercontent.com/assets/8291759/12960704/a653faa0-d062-11e5-9088-6526fa6fbac9.png)

However, when using a [markdown plugin for firefox](https://github.com/Thiht/markdown-viewer), the image is visible properly like so - 
![part33](https://cloud.githubusercontent.com/assets/8291759/12960748/ed6f3260-d062-11e5-830b-f337a78963c9.png)

However, when using the absolute path instead of relative path the image is visible.
Using absolute path - 
![part44](https://cloud.githubusercontent.com/assets/8291759/12960907/c57c1768-d063-11e5-8110-eb866ba4fb60.png)
the image is visible.
![part55](https://cloud.githubusercontent.com/assets/8291759/12960920/cf337a6c-d063-11e5-8b1f-8847e7a96056.png)

**Comment by nadavc** [comment]
:+1:

**Comment by alesny** [comment]
I have the same problem that local relative links does not work in the preview.

**Comment by mindplay-dk** [comment]
This would be really useful - it works on GitHub, so it would be natural to expect it to work here as well.

**Comment by demotodo** [comment]
What's the status of this? Is there any plan to support this?

**Comment by ShyykoSerhiy** [comment]
It will be supported in next release. It's scheduled on February 5th.

**Comment by demotodo** [comment]
@ShyykoSerhiy I made a pull request for this, https://github.com/ShyykoSerhiy/gfm-plugin/pull/119. Could you have a look when you are available? Thanks!

**Comment by ShyykoSerhiy** [comment]
That's awesome.

**Comment by ShyykoSerhiy** [comment]
fixed by https://github.com/ShyykoSerhiy/gfm-plugin/pull/119
