### ISSUE TITLE
Side-by-side code and preview

### ISSUE THREAD

**Issue by fgblomqvist** [ShyykoSerhiy/gfm-plugin#127]
I don't know if this is possible, but would be pretty sweet if this plugin would have the side-by-side code and preview like the other big markdown plugins.

**Comment by ShyykoSerhiy** [comment]
Is this the ~droid~ side by side editor you're looking for?
![recording](https://user-images.githubusercontent.com/1106995/32344719-2e71a164-bfde-11e7-9e7c-6beb637516ff.gif)

**Comment by fgblomqvist** [comment]
Clever, didn't think of that. Thanks!
