### ISSUE TITLE
Option to merge/replace Markdown preview tab with gfm tab

### ISSUE THREAD

**Issue by binkley** [ShyykoSerhiy/gfm-plugin#42]
Enjoy the plugin, thanks!

Provide an option to replace the Markdown Preview tab with the gfm tab.  Having two preview tabs is distracting/confusing.

**Comment by ShyykoSerhiy** [comment]
![replace](https://cloud.githubusercontent.com/assets/1106995/6991984/39ae5aa4-dabc-11e4-94f1-e40a9f6c28ce.png)
implemented in v0.1.3

**Comment by binkley** [comment]
That was quick, thanks!

**Comment by binkley** [comment]
Look good.  :)
