### ISSUE TITLE
CJK Support

### ISSUE THREAD

**Issue by MonsterSupreme** [ShyykoSerhiy/gfm-plugin#57]
The preview is much better than another plugin (markdown). :-)

However, Chinese characters could not be rendered.

**Comment by ShyykoSerhiy** [comment]
Hi, thanks for contributing to gfm-plugin. Can you please, attach file(or part of it) which isn't rendered?

**Comment by ShyykoSerhiy** [comment]
It looks like a problem with offline generations(which is enabled by default). Meanwhile you can disable offline generation and it will render just fine(it uses GitHub api in that case). 
![offline](https://cloud.githubusercontent.com/assets/1106995/7226834/b9b806c4-e754-11e4-9c3b-bb6faa48f60e.png)
