### ISSUE TITLE
Simple Web Viewer

### ISSUE THREAD

**Issue by zchee** [ShyykoSerhiy/gfm-plugin#60]
Hi,
I'm always using this plugin. Thanks.

BTW, I'm looking for simple web-view tab in Intellij IDE.
but, not found such plugin currently now.
For example, the coding while watching a tutorial on the web site.

I think that it make if you slightly change this plugin.
Are there any plans to implement such a function?

Please consider that.
Thanks.

**Comment by ShyykoSerhiy** [comment]
Hi, yes it'll be easy to implement. Meanwhile you can create md file with link to tutorial. Thanks for idea.

**Comment by zchee** [comment]
I'm expecting you a lot !
Thanks :)

**Comment by ShyykoSerhiy** [comment]
Implemented in 0.1.6.
