### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by PoziWorld** [ShyykoSerhiy/gfm-plugin#64]
Hello,

Can you please include a support for dispaying Cyrillic in .md files?

Thank you in advance.

P.S. Useful plugin!

**Comment by ShyykoSerhiy** [comment]
Hello,
Thanks for contributing. Next release will have cyrillic support.

**Comment by ShyykoSerhiy** [comment]
Can you provide some md file with Cyrillic text for testing?

**Comment by PoziWorld** [comment]
https://github.com/PoziWorld/PoziTone/blob/develop/README_ru.md
https://github.com/poziworld/PoziTone/blob/develop/HISTORY_ru.md

It's a weird thing, yesterday when I first switched rendering engine to JavaFX WebView, in one of two open files Cyrillic showed up, so I switched it a few more times, but I wouldn't show up again in any of those two files.

Now I have JxBrowser chosen, and in the second file it shows Cyrillic, but not in the one it showed up the first time...

**Comment by PoziWorld** [comment]
Hello, 

Any update on this issue?

Thanks.

**Comment by ShyykoSerhiy** [comment]
@PoziWorld, can you please try to disable ''Use offline generation" option inside Gfm settings.

**Comment by PoziWorld** [comment]
When it's enabled, the first time I open a Cyrillic document, it works fine. But when I change something in that document, and then go back to the preview, it no longer works.

When it's disabled, it doesn't work at all. Not event the first time.

It is the same for all rendering engines.

**Comment by ShyykoSerhiy** [comment]
That's odd. Can you please provide your OS version and Itellij(Webstor, phpstorm,...) version. Can you please check that you have version 0.1.8 of GFM plugin installed?

**Comment by PoziWorld** [comment]
Windows 7
PhpStorm PS-143.129
GFM 0.1.8

**Comment by ShyykoSerhiy** [comment]
Should be fixed in v0.1.9

**Comment by PoziWorld** [comment]
It works in offline mode. Thank you!

**Comment by PoziWorld** [comment]
Actually, in both modes. But when I first tried it after upgrading, the plugin wasn't in offline mode, when added some text in .md file and switched to preview, it showed some exception. Sorry, didn't take a screenshot. Can't replicate it anymore.
