### ISSUE TITLE
What does this plugin do?

### ISSUE THREAD

**Issue by Saeven** [ShyykoSerhiy/gfm-plugin#66]
I installed into PHPStorm, hopeful I'd have a new extension/editor with which to open .md files, but seems it isn't that simple.

**Comment by ShyykoSerhiy** [comment]
Hi, it adds one more tab below the editor to show preview for markdown file(to show how it will look on GitHub). That's it. If you don't have that tab as on preview thats a bug.  
![gfm](https://cloud.githubusercontent.com/assets/1106995/8394256/1bf68a0e-1d38-11e5-979d-4f82794c76cf.png)

**Comment by Saeven** [comment]
Through a flurry of PHPStorm restarts and plugin reinstalls - it works.  Nice!
