### ISSUE TITLE
Syntax coloring would be a really nice enhancement!

### ISSUE THREAD

**Issue by Saeven** [ShyykoSerhiy/gfm-plugin#67]
Within Github, you can do:

(three back-ticks)php

for example, to get php keywords colored within the code block.  I think Github uses Linguist https://github.com/github/linguist

**Comment by mindplay-dk** [comment]
I have been using [highlight.js](https://highlightjs.org/) to syntax-highlight my .md-files from GitHub, it works very nicely.

I don't know if the syntax highlighting is identical to that of GitHub - probably not - but it does ship with a GitHub color theme, which was close enough for me.

It would probably be a lot simpler to integrate this, than having to call out to Ruby? - basically, just drop in the JS and CSS assets, add one lines of JS to hook it up, and you should be good to go.
