### ISSUE TITLE
IDE Fatal Error: IPC process exited. Exit code: 127

### ISSUE THREAD

**Issue by marcotaubmann** [ShyykoSerhiy/gfm-plugin#69]
Each time I try to open a markdown file while only gfm-plugin is active, I get a green editor and this error:

    IPC process exited. Exit code: 127
    com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: IPC process exited. Exit code: 127
        at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)

How can i fix that?

Here are some information on my system that may help:

    gfm Version: 0.1.4

    PHPStorm 9.0 Build #PS-141.1912, built on July 7, 2015

    java version "1.7.0_79"
    OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu1)
    OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

    Chromium Version 43.0.2357.130 Ubuntu 15.04 (64-bit)

**Comment by ShyykoSerhiy** [comment]
Hi. It can be issue with jxbrowser component. Can you, please try to change rendering engine to loboevolution? Sometimes jxbrowser doesn't work on some Linux distros.

**Comment by ShyykoSerhiy** [comment]
Here https://groups.google.com/a/teamdev.com/forum/#!msg/jxbrowser-forum/gCXWabZiio4/8HkJnMz35k8J
The team behind jxbrowser explains the issue. I’ll be able to fix your problem when they fix it on their side. Meanwhile(if it actually a bug) with jxbrowser you can use loboevolution in settings(or javafx if you have Oracle java 8 to run with it Phpstorm).

**Comment by ShyykoSerhiy** [comment]
![settings](https://cloud.githubusercontent.com/assets/1106995/8776710/d6c2c8dc-2efb-11e5-99a3-6854b63b4416.gif)

**Comment by marcotaubmann** [comment]
That worked. Thank you for your fast and detailed response!

**Comment by ShyykoSerhiy** [comment]
Glad it worked. But keep in mind that loboevolution is a bit slow and has some drawbacks (https://github.com/ShyykoSerhiy/gfm-plugin/issues/32). I'll keep the issue open until fixed. 
Connected issue: https://github.com/ShyykoSerhiy/gfm-plugin/issues/63

**Comment by ShyykoSerhiy** [comment]
Fixed in v0.1.5 https://github.com/ShyykoSerhiy/gfm-plugin/releases/tag/v0.1.5.
You can use JxBrowser in v0.1.5 which is better than loboevolution.
