### ISSUE TITLE
Doesnt work with Mac and IntelliJ 15 Preview (JNA incompatibility)

### ISSUE THREAD

**Issue by svox1** [ShyykoSerhiy/gfm-plugin#91]
Hi,

thx for this plugin!

With 
- Mac (Yosemite)
- Java
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
- IntelliJ Ultimate 15 Preview

the plugin shows only a blank white page. No errors.

The new version from yesterday doesnt solved this problem. :(

Regards,
Sebastian

**Comment by ShyykoSerhiy** [comment]
should be fixed in 0.1.8

**Comment by ShyykoSerhiy** [comment]
you can try out it now

**Comment by svox1** [comment]
Wow that was quick! Thx it works!
