### ISSUE TITLE
updating to 0.1.8 yields Exception about `trustAnchors`

### ISSUE THREAD

**Issue by bronsen** [ShyykoSerhiy/gfm-plugin#94]
Pycharm 4.5.4 notified me of the update. When actually updating I get an error dialog stating:

    Plugin gfm was not installed: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

![2015-10-08-081553_1242x125_scrot](https://cloud.githubusercontent.com/assets/170530/10359108/8533d924-6d95-11e5-9c5c-fae78cf25347.png)

Clicking OK leaves 0.1.6 installed.

This is with pycharm 4.5.4, oracle java 1.8.0 update 60, ubuntu 14.04.3

What should I look into to get `gfm` updated?

**Comment by ShyykoSerhiy** [comment]
I've tried to reproduce, but had no luck. Can you please try this options?:
 * Go to https://plugins.jetbrains.com/plugin/7701?pr=phpstorm and download manually and install manually.
or
 * Remove plugin from phpstorm and install it from scratch. 
Anyway 1.7 and 1.8 releases include fixes for running on Windows 10 and Intellij Idea 15 preview(No new functionality). 
If you have feature request fill free to open an issue:)

Thx.
